# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: studio4096
email: contact@studio4096.com
description: > # this means to ignore newlines until "baseurl:"
    東京で活動中のイラストレーター／プログラマーです
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.studio4096.com" # the base hostname & protocol for your site
twitter_username: studio4096
github_username:  studio4096

# Build settings
markdown: kramdown

destination: public
source: src
exclude:
  - ".bowerrc"
  - "bower.json"
  - "bower_components"
  - ".gitignore"
  - ".sass-cache"
  - "README.md"
  - "bs-config.json"
  - "node_modules"
  - "package.json"
  - "webpack"
  - "webpack.config.js"
  - "src/_posts/2016-05-22-welcome-to-jekyll.markdown"
  - "src/about.md"
  - "src/index.html"
  - "src/about-us/index.md"
