version: "3.7"
services:
  frontend:
    container_name: studio4096_front
    image: "node:lts-alpine"
    #image: "node:lts-slim"
    #image: "node:lts-alpine"
    #build: 
    #  context: .
    #  args: 
    init: true
    user: "root"
    working_dir: /var/app
    env_file:
      - .env
      - lang.env
    environment:
      NODE_ENV: ${NODE_ENV}
      PARCEL_WORKERS: 1
      PS1: '[\u]\w # '
    volumes:
      - ./:/var/app
    expose:
      - "1234" # for HTTP
      - "5050" # for HMR
    ports:
      - "1234:1234"
      - "5050:5050"
    command: "sh -c 'apk add yarn && tail -f /dev/null'"
    #command: "tail -f /dev/null"
